### PR TITLE
Update eslint files

### PR DESCRIPTION
**Pull request by simnalamburt**
1.  Prevent eslint from looking in parent folders to the root

    By default, ESLint will look for configuration files in all parent folders up to the root directory. Preventing it from doing so. This is may cause weird bug.

2.  The use of `.eslintrc` has been deprecated. Replacing with `.eslintrc.yml`

    You may ask... *"Why Yaml?"*
    JSON cannot contain any comment and unnecessarily restricted. My personal best choice is [TOML] but it's unavailable for eslint so I choosed Yaml.

[TOML]: https://github.com/toml-lang/toml

###### Reference
- https://arp242.net/weblog/json_as_configuration_files-_please_dont

### CODE REVIEW

**Comment by noraesae** [comment]
LGTM

**Comment by noraesae** [comment]
Could you check DM I have just sent on the messenger?

**Comment by simnalamburt** [comment]
@noraesae Which DM? I've nothing received

**Comment by noraesae** [comment]
Sorry, I meant LINE.

**Pull request merged**
